version: '4.4'

x-common-variables: &common-variables
  CYCLONEDDS_URI: <CycloneDDS><Domain><Discovery><MaxAutoParticipantIndex>1000</MaxAutoParticipantIndex></Discovery><General><Interfaces><NetworkInterface
    name="lo" multicast="true"/></Interfaces></General></Domain></CycloneDDS>
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
  ROS_DOMAIN_ID: '0'


services:
  bin-picking-mockup:
    image: bin-picking-mockup:latest
    command: /bin/bash -c "ros2 run bin_picking_mockup bin_picking_mockup_node"
    network_mode: host
    environment: *common-variables

  robot-api:
    image: bin-picking-mockup:latest
    command: python3 -m uvicorn robot_adapter:app --host 0.0.0.0 --port 8081
    network_mode: host
    environment: *common-variables

  wms-api:
    image: bin-picking-mockup:latest
    command: python3 -m uvicorn wms_api:app --host 0.0.0.0 --port 8080
    network_mode: host
    environment:
      <<: *common-variables
      ROBOT_BASE_URL: ${ROBOT_BASE_URL}
  hmi:
    image: bin-picking-mockup:latest
    command: /bin/bash -c "nginx && tail -f /var/log/nginx/*.log"
    network_mode: host
